### ISSUE TITLE
KeyboardInterrupt is not handled and changes the return code

### ISSUE THREAD

**Issue by aminfara** [illBeRoy/taskipy#7]
I have a task `server` defined as follows:

```toml
[tool.taskipy.tasks]
server = "uvicorn main:app --reload"
```
when I press `CTRL+C` to exit `uvicorn` server I get an exception traceback and return code to shell is `130`.

```
$ poetry run task server
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
...
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [65600]
INFO:     Stopping reloader process [65598]
Traceback (most recent call last):
  File "/Users/ali/Workspace/testproj/.venv/bin/task", line 10, in <module>
    sys.exit(main())
  File "/Users/ali/Workspace/testproj/.venv/lib/python3.8/site-packages/taskipy/cli.py", line 11, in main
    run_task(args.name, args.args)
  File "/Users/ali/Workspace/testproj/.venv/lib/python3.8/site-packages/taskipy/run.py", line 57, in run_task
    exit_code = run_commands_and_bail_on_first_fail(commands)
  File "/Users/ali/Workspace/testproj/.venv/lib/python3.8/site-packages/taskipy/run.py", line 12, in run_commands_and_bail_on_first_fail
    p.wait()
  File "/Users/ali/.pyenv/versions/3.8.1/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/Users/ali/.pyenv/versions/3.8.1/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/Users/ali/.pyenv/versions/3.8.1/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

$ echo $?
130
```

However if I run `uvicorn` directly with `poetry` it shutdown gracefully and return value is `0`.

```
$ poetry run uvicorn main:app --reload
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [65153]
INFO:     Started server process [65172]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [65172]
INFO:     Stopping reloader process [65153]

$ echo $?
0
```

Taskipy changes exit code of `uvicorn` which is not desired behaviour.

**Comment by illBeRoy** [comment]
Hey!
Thanks for reaching out, I'm looking into this.

**Comment by illBeRoy** [comment]
A version including the possible fix for your bug was released (1.1.3)
I would appreciate if you could try it out and confirm that it now works properly :)
Thanks

**Comment by illBeRoy** [comment]
Hey there, @aminfara! Do you have any good news for me? :)
Thanks!

**Comment by aminfara** [comment]
Roy,

Thanks for very prompt response on this. I just updated taskipy to 1.1.3 and I confirm that KeyboardInterrupt is now managed properly. Please feel free to close the issue. 👏

**Comment by illBeRoy** [comment]
Great! Glad to hear. Closing this issue.
